### ISSUE TITLE
Jumping next to fences => false positive

### ISSUE THREAD

**Issue by antbig** [heirteir/AutoEye#7] opened 2018-04-21 12:18 UTC
Detected for "spoofed on ground" and "invalid motion" when jumping next to not full block (fence, anvil)
https://youtu.be/wq_iyQXWaxU

**Comment by Alex1607** [comment] 2018-04-21 15:06
I couldn't reproduce that. Did you do something else before the error occurred? https://dl.pluoi.com/5adb534052aca.mp4

**Comment by antbig** [comment] 2018-04-21 15:09
No, i'm playing in 1.12.2 on an 1.8.8 server using viaversion

**Comment by Alex1607** [comment] 2018-04-21 15:14
Strange. It looks like it is just an issue if the player is using 1.12.2. I have just tested it again with 1.12.2 and viaversion and it flagged me too. https://dl.pluoi.com/5adb55478d692.mp4

**Comment by heirteir** [comment] 2018-04-22 04:29
Fixed in AutoEye version 0.66A

**Closed as completed by heirteir** 2018-04-22 04:29 UTC
Labels: fixed
