### ISSUE TITLE
Invalid Motion Spam on teleport

### ISSUE THREAD

**Issue by topthat177** [heirteir/AutoEye#17] opened 2018-04-24 10:52 UTC
So with version 0.66C - whenever a player teleports from one world to another either via /tp or /spawn etc. when they land in the new world, when they try and walk they get rubber banded back to their teleport location and autoeye constantly spams Invalid Motion warnings even if they have stopped trying to walk. However if they have access to /fly and fly from their teleport location it stops spamming.

**Plugin Version:**
0.66C
**Server Version:**
1.12.2
**Minecraft Version:**
1.12.2
**Other Plugins:**
CleanroomGenerator, BlockLocker, PlaceholderAPI, TuxTwoLib, WhitelistPlus, GMC, UltimateVotes, SimpleBackup, CoreProtect, WorldEdit, FirstJoinPlus, PacketListenerApi, NoPluginViewer, Votifier, ProtocolLib, Multiverse-Core, LibsDisguises, AdvancedPortals, CustomUknownCommand, DeluxeMenus, PermissionsEx, CustomHelp, SnowballDamage, Multiverse-Portals, ProtocolSupport, CommandButtons, ClientStats, HolographicDisplays, Mazerunner, WorldGuard, ProtocolSupportLegacySupport, Multiverse-NetherPortals, ProtocolSupportStuff, Vault, UltraCosmetics, PlayerWarpGUI, PerWorldInventory, SkyWars, BetterRTP, Essentials, WarpGUI, Jobs, Citizens, AdvancedAchievements, EssentialsChat, EnjinMinecraftPlugin, Quests, EssentialsProtect, EssentialsSpawn, WorldGuardExtraFlags

**Does the Server use ViaVersion?:**
No, but we use protocolsupport.
**Console output** (_If the plugin throw an error in the console post the log here. Please use a [gist](https://gist.github.com/) or [pastebin](https://pastebin.com)_):
No console output.

**Comment by Alex1607** [comment] 2018-04-24 11:10
I have a feeling what might be causing it, try teleporting the player but teleport him to the same Y coordinate as he is at the moment.

**Comment by topthat177** [comment] 2018-04-24 22:45
Kavatch, so teleport from world A to world B and make sure you land at the same Y value and see what happens? Is that what your asking?

**Comment by Alex1607** [comment] 2018-04-24 22:47
Yea just do the same as before but try to get on the same Y value

**Comment by topthat177** [comment] 2018-04-25 10:21
That is irrelevant Kavatch - Check your Discord DM

**Comment by topthat177** [comment] 2018-04-25 10:22
Also Spamming sometimes on server join and jumping doesn't seem to stop it, only flying.

**Comment by Alex1607** [comment] 2018-04-25 10:39
I think I know what it is then. I'll check it out this evening.
Also flying stops it because if a player is flying he is not checked and it shows that it can't be the first if check.

**Comment by topthat177** [comment] 2018-04-25 10:40
Heirteir - Here is the video for this issue: https://vimeo.com/266468245

Password = autoeye

**Comment by Alex1607** [comment] 2018-04-25 19:43
Some happens with portals without any plugin. And also when the player joins.
And please close this issue: https://github.com/heirteir/AutoEye/issues/20 it is a duplicate. Since both errors are caused by the same problem.

**Comment by heirteir** [comment] 2018-04-26 00:04
Will be fixed in the next commit.

**Closed as completed by heirteir** 2018-04-26 00:04 UTC
Labels: fixed
